install.packages("Rcpp11", repos = "http://cran.uk.r-project.org")
install.packages("Rcpp", repos = "http://cran.uk.r-project.org")
install.packages("knitr", repos = "http://cran.uk.r-project.org")
install.packages("rmarkdown", repos = "http://cran.uk.r-project.org")
install.packages("testthat", repos = "http://cran.uk.r-project.org")
install.packages("ggplot2", repos = "http://cran.uk.r-project.org")
