install.packages("ape", repos = "http://cran.uk.r-project.org")
install.packages("adephylo", repos = "http://cran.uk.r-project.org")
install.packages("data.table", repos = "http://cran.uk.r-project.org")
install.packages("devtools", repos = "http://cran.uk.r-project.org")
install.packages("ggplot2", repos = "http://cran.uk.r-project.org")
install.packages("gridExtra", repos = "http://cran.uk.r-project.org")
install.packages("knitr", repos = "http://cran.uk.r-project.org")
install.packages("lintr", repos = "http://cran.uk.r-project.org")
install.packages("phangorn", repos = "http://cran.uk.r-project.org")
install.packages("PBD", repos = "http://cran.uk.r-project.org")
install.packages("rmarkdown", repos = "http://cran.uk.r-project.org")
install.packages("testit", repos = "http://cran.uk.r-project.org")
install.packages("testthat", repos = "http://cran.uk.r-project.org")
install.packages("XML", repos = "http://cran.uk.r-project.org")
devtools::install_github("richelbilderbeek/beastscriptr")
devtools::install_github("richelbilderbeek/rBEAST")
devtools::install_github("richelbilderbeek/ribir")
