library(testthat)
library(Cer2016)

test_check("Cer2016", filter = "add_")
test_check("Cer2016", filter = "alignment_")
test_check("Cer2016", filter = "are_")
test_check("Cer2016", filter = "collect_")
test_check("Cer2016", filter = "convert_")
test_check("Cer2016", filter = "create_")
test_check("Cer2016", filter = "do_")
test_check("Cer2016", filter = "extract_")
test_check("Cer2016", filter = "find_")
test_check("Cer2016", filter = "get_")
test_check("Cer2016", filter = "has_")
test_check("Cer2016", filter = "is_")
test_check("Cer2016", filter = "nrbs_")
test_check("Cer2016", filter = "plot_")
test_check("Cer2016", filter = "read_")
test_check("Cer2016", filter = "save_")
test_check("Cer2016", filter = "show_")