---
title: "add_posteriors demo"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{add_posteriors demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Starting up

We will need to load some libraries:

```{r}
library(ape)
library(Cer2016)
library(ggplot2)
library(Hmisc)
library(nLTT)
library(ribir)
library(phangorn)
```

We also set the resolution of our analysis:

```{r}
dt <- 0.001
```

## Creating parameter files

Here, we create the four parameter filenames:

```{r}
filename <- "add_posterior_demo.RDa"
```

To be sure to have a fresh analysis, we delete the files if they exist:

```{r}
if (file.exists(filename)) {
  file.remove(filename)
}
```

Now the parameter files are created with the desired parameters:

```{r}
rng_seeds <- seq(1,4)
sirgs <- rep(0.5, times = 4)
siris <- rep(0.5, times = 4)
scrs <- c(1.0e6, 1.0e-1, 1.0e6, 1.0e-1)
ergs <- rep(0.1, times = 4)
eris <- rep(0.1, times = 4)
ages <- rep(5, times = 4)
n_species_trees_sampleses <- c(1, 1, 2, 2)
mutation_rates <- rep(0.01, times = 4)
n_alignmentses <- c(1, 1, 2, 2)
sequence_lengths <- rep(1000, times = 4)
mcmc_chainlengths <- rep(10000, times = 4)
n_beast_runses <- c(1, 1, 2, 2)

save_parameters_to_file(
  rng_seed = 2,
  sirg = 0.5,
  siri = 0.5,
  scr = 1.0e-1,
  erg = 0.1,
  eri = 0.1,
  age = 5,
  n_species_trees_samples = 1,
  mutation_rate = 0.01,
  n_alignments = 1,
  sequence_length = 1000,
  mcmc_chainlength = 10000,
  n_beast_runs = 1,
  filename = filename
)  
testit::assert(is_valid_file(filename))
```

Get there:

```{r}
add_pbd_output(filename)
add_species_trees_with_outgroup(filename)  
add_alignments(filename)  
add_posteriors(filename, skip_if_output_present = TRUE)
```

Let's see the alignment:

```{r}
plot_alignments(filename)
```

Show the posterior:

```{r}
trees_filename <- "add_posterior_demo_1_1_1.trees"
testit::assert(file.exists(trees_filename))
phylogenies <- rBEAST::beast2out.read.trees(trees_filename)
# To get the densiTree function working, phylogenies must be of class multiphylo
class(phylogenies) <- "multiPhylo"
```


```{r fig.width = 7, fig.height = 7}
densiTree(
  phylogenies, 
  type = "cladogram", 
  alpha = 1/length(phylogenies)
)
```

