---
title: "Analyse nLTTs"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyse nLTTs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Loading this package

```{r}
library(Cer2016)
```

## Collecting nLTTs from all files

```{r}
csv_filename_species_trees <- find_path("collected_nltts_species_trees.csv")
csv_filename_posterior <- find_path("collected_nltts_posterior.csv")
testit::assert(file.exists(csv_filename_species_trees))
testit::assert(file.exists(csv_filename_posterior))
```

Loading it from file:

```{r}
df_species_trees <- read.csv(
 file = csv_filename_species_trees, 
 header = TRUE, 
 stringsAsFactors = FALSE, 
 row.names = 1
)
df_species_trees$species_tree <- as.factor(df_species_trees$species_tree)

df_posterior <- read.csv(
 file = csv_filename_posterior, 
 header = TRUE, 
 stringsAsFactors = FALSE, 
 row.names = 1
)

df_posterior$species_tree <- as.factor(df_posterior$species_tree)
df_posterior$alignment <- as.factor(df_posterior$alignment)
df_posterior$beast_run <- as.factor(df_posterior$beast_run)

```

Putting the head of the data frame in a table:

```{r}
knitr::kable(head(df_species_trees))
```

```{r}
knitr::kable(head(df_posterior))
```

What kind of data is `df_species_trees`?

```{r}
str(df_species_trees)
names(df_species_trees)
```

What kind of data is `df_posterior`?

```{r}
str(df_posterior)
names(df_posterior)
```

Let's first plot the distribution of nLTTs:

```{r}
filenames <- as.vector(sapply(unique(sort(df_species_trees$filenames)), Cer2016::find_path))
for (filename in filenames) {
  #plot_species_tree(filename)
  plot_species_tree_nltt(filename, dt = 0.1)
}
```

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = df_species_trees, 
  ggplot2::aes(x = df_species_trees$t, y = df_species_trees$nltt, colour = df_species_trees$species_tree)
) + ggplot2::geom_point() + ggplot2::geom_smooth()
```


## Some pretty nonsensical histograms

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = df_species_trees, 
  ggplot2::aes(df_species_trees$nltt, fill = df_species_trees$species_tree)
) + ggplot2::geom_histogram(
  alpha = 0.25, 
  position = 'identity', 
  binwidth = 0.1
)
```

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = df_species_trees, 
  ggplot2::aes(df_species_trees$nltt, fill = df_species_trees$species_tree)
) + ggplot2::geom_density(
  alpha = 0.25, 
  position = 'identity'
)
```







```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = df_posterior, 
  ggplot2::aes(df_posterior$nltt, fill = df_posterior$species_tree)
) + ggplot2::geom_histogram(
  alpha = 0.25, 
  position = 'identity', 
  binwidth = 0.1
)
```

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = df_posterior, 
  ggplot2::aes(df_posterior$nltt, fill = df_posterior$species_tree)
) + ggplot2::geom_density(
  alpha = 0.25, 
  position = 'identity'
)
```




```{r}
ggplot2::ggplot(
  data = df_posterior, ggplot2::aes(df_posterior$nltt)
) + ggplot2::geom_histogram(binwidth = 1)
```
