---
title: "Analyse gamma's"
author: "Richel Bilderbeek, Femke Thon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyse gamma's}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Loading this package

```{r}
library(Cer2016)
library(ggplot2)
```

## Collecting gamma's from all files

```{r collecting_gammas6}
csv_filename_species_trees <- "collected_gammas_species_trees.csv"
csv_filename_posterior     <- "collected_gammas_posterior.csv"
zip_filename_posterior     <- "collected_gammas_posterior.csv.zip"
csv_filename_parameters    <- "collected_parameters.csv"
zip_filename_comparison    <- "femke.csv.zip"
csv_filename_comparison    <- "femke.csv"
create_fresh <- FALSE # Set this to TRUE and for a >60 mins calculation
if (create_fresh) {
  folder <- "/home/p230198/Peregrine"
  all_parameter_filenames <- paste(
    folder, list.files(folder, pattern = "\\.RDa"), sep = "/"
  )
  df <- collect_files_gammas(all_parameter_filenames, verbose = TRUE)
  write.csv(
    x = df$species_tree_gamma_stats,
    file = csv_filename_species_trees,
    row.names = TRUE
  )
  write.csv(
    x = df$posterior_gamma_stats,
    file = csv_filename_posterior,
    row.names = TRUE
  )
}
if (!file.exists(csv_filename_posterior)) {
  utils::unzip(zip_filename_posterior)
}
if (!file.exists(csv_filename_comparison)) {
  utils::unzip(zip_filename_comparison)
}
testit::assert(file.exists(csv_filename_species_trees))
testit::assert(file.exists(csv_filename_posterior))
testit::assert(file.exists(csv_filename_parameters))
testit::assert(file.exists(csv_filename_comparison))
```

Note that the comma-seperated file is only created when absent,
as this is a long step.

Loading it from file:

```{r loading_files}
df_species_trees <- read.csv(
 file = csv_filename_species_trees, 
 header = TRUE, 
 stringsAsFactors = FALSE, 
 row.names = 1
)

df_posterior <- read.csv(
 file = csv_filename_posterior, 
 header = TRUE, 
 stringsAsFactors = FALSE, 
 row.names = 1
)

df_parameters <- read.csv(
  file = csv_filename_parameters, 
  header = TRUE, 
  stringsAsFactors = FALSE, 
  row.names = 1
)

df_comparison <- read.csv(
  file = csv_filename_comparison,
  header = TRUE,
  stringsAsFactors = FALSE,
  row.names = 1
)

```

Analysis here:

```{r}
class(df_comparison)
class(df_parameters)

# Add a column called 'filenames' to the parameter files
df_parameters$filenames <- rownames(df_parameters)

names(df_comparison)
names(df_parameters)
df_big <- merge(x = df_parameters, y = df_comparison, by = "filenames", all = TRUE)

names(df_big)
knitr::kable(head(df_big))
df_big$speciation_completion_rate <- as.factor(df_big$speciation_completion_rate)

ggplot(df_big, aes(x = diff, colour = speciation_completion_rate)) + 
  geom_density() +
  xlim(c(-2, 2))
```


