---
title: "Analyse nLTT statistics"
author: "Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Analyse nLTTs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Abstract

This vignette shows how analyse the nLTT statistics.

## Setup

Loading this package

```{r}
library(Cer2016)
options(warn = 2)
```

## Show the distribution of nLTT statistics

```{r}
nltt_stats_raw <- read_collected_nltt_stats()
#nltt_stats_raw$sti <- plyr::revalue(nltt_stats_raw$sti, c("1"="youngest", "2"="oldest"))
knitr::kable(head(nltt_stats_raw))
```

Remove the NA's:

```{r}
nltt_stats <- nltt_stats_raw[!is.na(nltt_stats_raw$nltt_stat), ]
```

All on one heap:

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = nltt_stats,
  ggplot2::aes(
    x = nltt_stats$filename,
    y = nltt_stats$nltt_stat
  )
) + ggplot2::geom_boxplot(
) + ggplot2::scale_x_discrete(
  name = "Filename"
) + ggplot2::scale_y_continuous(
  name = "nLTT statistic"
) + ggplot2::ggtitle("Distribution of nLTT statistics") + 
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, vjust = 0.5)) + ggplot2::theme(legend.position="none") + 
  ggplot2::theme(axis.ticks = ggplot2::element_blank(), axis.text.x = ggplot2::element_blank())

```

Seperated by species tree, but still at one big heap:

```{r fig.width = 7, fig.height = 7}
ggplot2::ggplot(
  data = nltt_stats,
  ggplot2::aes(
    x = nltt_stats$sti,
    y = nltt_stats$nltt_stat
  )
) + ggplot2::geom_boxplot(
) + ggplot2::scale_x_discrete(
  name = "Species tree index"
) + ggplot2::scale_y_continuous(
  name = "nLTT statistic"
) + ggplot2::ggtitle("Distribution of nLTT statistics")

```

