---
title: "display dataset parameters"
author: "Jolien Gay en Richel Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Code Info

```{r}
library(Cer2016)

pcname <- system('uname -n', intern = TRUE) 
# User    | PC name 
# --------+-------------------
# Jolien  | ?Aline
# Richel  | fwn-biol-132-102"

```

# Richel's work

Here is a test:

```{r}
if (pcname == "fwn-biol-132-102" || pcname == "druten") {
  parameter_filename_a <- find_path("article_0_0_0_0_0.RDa")
  parameter_filename_b <- find_path("article_0_1_4_0_2.RDa")
  parameter_filename_c <- find_path("toy_example_1.RDa")
  all_parameter_filenames <- c(parameter_filename_a, parameter_filename_b, parameter_filename_c)
  show_parameter_files(all_parameter_filenames)
}
```

Here is a test in the true folder

```{r}
if (pcname == "fwn-biol-132-102" || pcname == "druten") {
  folder <- "/home/p230198/Peregrine"
  parameter_filenames <- paste(
    folder, 
    c(
      "article_1_2_4_1_1.RDa",
      "article_2_2_4_1_1.RDa",
      "article_3_2_4_1_1.RDa"
    ), sep = "/")
  file.exists(parameter_filenames)
  print(names(readRDS(parameter_filenames[1])$parameters))
  #print(names(readRDS(parameter_filenames[2])$parameters)) # nolint this file cannot be read
  print(names(readRDS(parameter_filenames[3])$parameters))
  #file <- read_file(parameter_filenames[2])
  
  show_parameter_files(parameter_filenames, verbose = TRUE)
}
```

This is the result:

```{r}
if (pcname == "fwn-biol-132-102" || pcname == "druten") {
  folder <- "/home/p230198/Peregrine"
  all_parameter_filenames <- paste(folder, list.files(folder, pattern = "\\.RDa"), sep = "/")
  file.exists(parameter_filenames)
  show_parameter_files(head(all_parameter_filenames), verbose = TRUE)
}
```


## Jolien's work

```{r}
if (pcname == "Aline") {
  setwd("c:/Users/Aline/Peregrine")
  getwd()
  # Put all .RDA files in a variable
  all_parameters <- Sys.glob("*.RDa") # alternative, but longer: all_parameters <- list.files(pattern = "\\.RDa$", ignore.case=TRUE)
  print(all_parameters)
  
  file.exists(all_parameters)
  
  show_parameter_files(all_parameters)
}
```



```{r}
#---------------------Example---------------------------------
#filename <- filenames[1]
#filename <- "d:/Peregrine/article_0_0_0_0_0.RDa"
#filename <- "toy_example_1.RDa"
#readRDS(filename)
#file.exists(filename)
#file <- read_file(filename)
#names(file)

```