#' Samples species trees from PBD::pbd_sim its output
#' It does not use pbd_sim()$stree, but generates these like PBD does.
#' @param n The number of species trees to sample
#' @param pbd_sim_output The output generated by PBD::pbd_sim
#' @return A list of length n, containing the n sampled species trees
#' @export
#' @author Richel Bilderbeek, inspired by Rampal Etienne's PBD::pbd_sim function
sample_species_trees <- function(
  n, #How many?
  pbd_sim_output
) {
  if (!Cer2016::is_pbd_sim_output(pbd_sim_output)) {
    Cer2016::is_pbd_sim_output(pbd_sim_output, verbose = TRUE)
    stop("sample_species_trees: ",
      "pbd_sim_output is not output of PBD::pbd_sim"
    )
  }

  crown_age <- Cer2016::get_phylogeny_crown_age(
    phylogeny = pbd_sim_output$tree
  )
  # absL got renamed to abs_l
  abs_l <- pbd_sim_output$L0
  abs_l[, 2] <- abs(pbd_sim_output$L0[, 2])

  species_trees <- NULL
  for (i in c(1:n)) {
    # sL got renamed to s_l
    s_l <- PBD::sampletree(abs_l, crown_age)
    species_tree <- ape::as.phylo(
      ape::read.tree(text = PBD::detphy(s_l, crown_age))
    )
    species_trees <- c(species_trees, list(species_tree))
  }

  testit::assert(typeof(species_trees) == "list")
  testit::assert(length(species_trees) == n)
  testit::assert(n == 0 || class(species_trees[[1]]) == "phylo")

  species_trees
}
