#' Samples species trees from PBD::pbd_sim its output
#' It does not use pbd_sim()$stree, but generates these like PBD does.
#' @param n The number of species trees to sample
#' @param pbd_sim_output The output generated by PBD::pbd_sim
#' @return A list of length n, containing the n sampled species trees
#' @export
#' @author Richel Bilderbeek
sample_species_trees_from_pbd_sim_output <- function(
  n, #How many?
  pbd_sim_output
) {
  if (!is_pbd_sim_output(pbd_sim_output)) {
    is_pbd_sim_output(pbd_sim_output, verbose = TRUE)
    stop("sample_species_trees_from_pbd_sim_output: ",
      "pbd_sim_output is not output of PBD::pbd_sim"
    )
  }

  crown_age <- get_phylogeny_crown_age(pbd_sim_output$tree)
  absL = pbd_sim_output$L0
  absL[,2] = abs(pbd_sim_output$L0[,2])

  species_trees <- NULL
  for (i in c(1:n)) {
    sL = PBD::sampletree(absL,crown_age)
    species_tree = ape::as.phylo(ape::read.tree(text = PBD::detphy(sL,crown_age)))
    species_trees <- c(species_trees,list(species_tree))
  }

  testit::assert(typeof(species_trees) == "list")
  testit::assert(length(species_trees) == n)
  testit::assert(n == 0 || class(species_trees[[1]]) == "phylo")

  return (species_trees)
}